services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      volumes:
        - ../../:/workspace:cached
        - $HOME/.ssh:/home/vscode/.ssh:cached
      ports:
        - "3000:3000"
      command: sleep infinity